const applications = [{
    'ID': 1,
    'DateSuggest': '04/03/2021',
    'PeopleSuggest': 'Lê Hoài Nam',
    'DateMove': '20/03/2021',
    'Censor': 'Lê Việt Hoàng',
    'DateDone': '14/12/2021',
    'Place': 'TP Hồ Chí Minh',
    'Reason': 'Được phân công',
    'Status': 'Đã hoàn thành',
  }, 
  {
    'ID': 2,
    'DateSuggest': '04/03/2021',
    'PeopleSuggest': 'Lê Hoài Nam',
    'DateMove': '20/03/2021',
    'Censor': 'Lê Việt Hoàng',
    'DateDone': '14/12/2021',
    'Place': 'TP Hồ Chí Minh',
    'Reason': 'Được phân công',
    'Status': 'Đã hoàn thành',
  },{
    'ID': 3,
    'DateSuggest': '04/03/2021',
    'PeopleSuggest': 'Lê Hoài Nam',
    'DateMove': '20/03/2021',
    'Censor': 'Lê Việt Hoàng',
    'DateDone': '14/12/2021',
    'Place': 'TP Hồ Chí Minh',
    'Reason': 'Được phân công',
    'Status': 'Đã hoàn thành',
  },{
    'ID': 4,
    'DateSuggest': '04/03/2021',
    'PeopleSuggest': 'Lê Hoài Nam',
    'DateMove': '20/03/2021',
    'Censor': 'Lê Việt Hoàng',
    'DateDone': '14/12/2021',
    'Place': 'TP Hồ Chí Minh',
    'Reason': 'Được phân công',
    'Status': 'Đã hoàn thành',
  },{
    'ID': 5,
    'DateSuggest': '04/03/2021',
    'PeopleSuggest': 'Lê Hoài Nam',
    'DateMove': '20/03/2021',
    'Censor': 'Lê Việt Hoàng',
    'DateDone': '14/12/2021',
    'Place': 'TP Hồ Chí Minh',
    'Reason': 'Được phân công',
    'Status': 'Đã hoàn thành',
  },{
    'ID': 6,
    'DateSuggest': '04/03/2021',
    'PeopleSuggest': 'Lê Hoài Nam',
    'DateMove': '20/03/2021',
    'Censor': 'Lê Việt Hoàng',
    'DateDone': '14/12/2021',
    'Place': 'TP Hồ Chí Minh',
    'Reason': 'Được phân công',
    'Status': 'Đã hoàn thành',
  },{
    'ID': 7,
    'DateSuggest': '04/03/2021',
    'PeopleSuggest': 'Lê Hoài Nam',
    'DateMove': '20/03/2021',
    'Censor': 'Lê Việt Hoàng',
    'DateDone': '14/12/2021',
    'Place': 'TP Hồ Chí Minh',
    'Reason': 'Được phân công',
    'Status': 'Đã hoàn thành',
  },{
    'ID': 8,
    'DateSuggest': '04/03/2021',
    'PeopleSuggest': 'Lê Hoài Nam',
    'DateMove': '20/03/2021',
    'Censor': 'Lê Việt Hoàng',
    'DateDone': '14/12/2021',
    'Place': 'TP Hồ Chí Minh',
    'Reason': 'Được phân công',
    'Status': 'Đã hoàn thành',
  },{
    'ID': 9,
    'DateSuggest': '04/03/2021',
    'PeopleSuggest': 'Lê Hoài Nam',
    'DateMove': '20/03/2021',
    'Censor': 'Lê Việt Hoàng',
    'DateDone': '14/12/2021',
    'Place': 'TP Hồ Chí Minh',
    'Reason': 'Được phân công',
    'Status': 'Đã hoàn thành',
  },{
    'ID': 10,
    'DateSuggest': '04/03/2021',
    'PeopleSuggest': 'Lê Hoài Nam',
    'DateMove': '20/03/2021',
    'Censor': 'Lê Việt Hoàng',
    'DateDone': '14/12/2021',
    'Place': 'TP Hồ Chí Minh',
    'Reason': 'Được phân công',
    'Status': 'Đã hoàn thành',
  },{
    'ID': 11,
    'DateSuggest': '04/03/2021',
    'PeopleSuggest': 'Lê Hoài Nam',
    'DateMove': '20/03/2021',
    'Censor': 'Lê Việt Hoàng',
    'DateDone': '14/12/2021',
    'Place': 'TP Hồ Chí Minh',
    'Reason': 'Được phân công',
    'Status': 'Đã hoàn thành',
  },
];
  
  export default {
    getApplications() {
      return applications;
    }
  };
  